### ISSUE TITLE
Problem using seuratToLiger

### ISSUE THREAD

**Issue by ccruizm** [MacoskoLab/liger#102]
Good day,

I have been using your tools to analyze my scRNA data. Now, I would also like to use the Seurat object I have and run Liger on it and compare the results. However, I am having problems using  `seuratToLiger`. Once I want to run the function `ligerex = seuratToLiger(seurat.obj, combined.seurat = T, assays.use = 'RNA')` the next error appears: 

```
Error in createLiger(raw.data = raw.data, remove.missing = remove.missing): At least one cell name is repeated across datasets; please make sure all cell names
         are unique.
Traceback:

1. seuratToLiger(GBM, combined.seurat = T, assays.use = "RNA")
2. createLiger(raw.data = raw.data, remove.missing = remove.missing)
3. stop("At least one cell name is repeated across datasets; please make sure all cell names\n         are unique.")
```

I have checked the `colnames` in my Seurat object `any(duplicated(colnames(seurat.obj)))` and haven't found any duplicates. I am using Seurat v3 (according to the vignette this version is supported). Where do you think the problem is?

Thanks in advance for your help!

**Comment by vkozareva** [comment]
Hello @ccruizm! It seems like you're trying to convert a Seurat object here without specifying multiple assays or a metadata column on which to split the entire dataset (since you've set `assays.use = "RNA"`, that would pass along your entire RNA dataset). Unfortunately right now liger objects are not designed to take a single raw dataset (as opposed to multiple), which is why you're getting this unintended error about cell names being repeated. 

Try setting the `meta.var` parameter to a metadata column that can be used to split your dataset, instead of `assays.use` and see if that fixes the problem. Sorry that the function documentation was a little unclear on this point! We're also working on expanding liger's functionality so single datasets can be processed too, which should prevent this issue in the future.

**Comment by ccruizm** [comment]
Thanks @vkozareva for your help! Indeed, setting the `meta.var` allows me to load the Seurat object to process it by Liger.
