### ISSUE TITLE
makeRiverplot Error: Cluster Format?

### ISSUE THREAD

**Issue by shiwei-wang** [MacoskoLab/liger#106]
Hi!

I'm trying to draw a river plot of neurons from p2 and p11 mice cerebellum with annotated cluster assignment. However, this error comes up:
`Error in edge_list[[nodes1[i]]] <- temp : 
  attempt to select less than one element in OneIndex`

Is it possible that this is due to the incorrect data format of the cluster labels? Can you upload the tenx_seqwell_clusters.RDS file from PBMC walkthrough so I can look at your data format? Currently, my cluster labels file is a list with two columns: cell number and string annotation. The cell numbers in the labels are exact match with liger@H[[1]] and liger@H[[2]]. However, `p2_cluster[rownames(liger@H[[1]])]` gives `Error in '[.data.frame'(p2_cluster, rownames(liger@H[[1]])) : 
  undefined columns selected`

Thank you!

<img width="198" alt="Screen Shot 2019-08-21 at 17 32 28" src="https://user-images.githubusercontent.com/29617740/63473092-e115e800-c439-11e9-8ac5-adcb7910f3f1.png">

**Comment by vkozareva** [comment]
Hello! This error is likely due to a bug we accidentally introduced in our latest update, which should be fixed now. 
As for the cluster label format, they should just be factors with names that match the cell names of your liger object. In your case, the following might work: 
```
# Assuming your cell names in liger are numbers like your dataframe
# Comma allows you to index by row instead of column
p2_labels <- factor(p2_cluster[rownames(liger@H[[1]]), ])
names(p2_labels) <- rownames(liger@H[[1]])
``` 
You can also find tenx_seqwell_clusters.RDS with example cluster labels in our data files: [pbmc_alignment.zip](https://github.com/MacoskoLab/liger/tree/master/vignettes/pbmc_alignment.zip).

**Comment by shiwei-wang** [comment]
Hi!

This works perfectly! Thank you so much!

**Comment by Lei-Guo** [comment]
I have exact same problem. Below is my code. The names of clusters match the raw.data columns in the liger object.

```
ligerex_endo <- seuratToLiger(list(sub_endo, sub_E), names = c('sub_endo', 'sub_E'), num.hvg.info = 2000)

makeRiverplot(ligerex_endo, cluster1 = Idents(sub_endo), cluster2 = Idents(sub_E))

identical(colnames(ligerex_endo@raw.data$sub_endo), names(Idents(sub_endo))) #TRUE

identical(colnames(ligerex_endo@raw.data$sub_E), names(Idents(sub_E))) #TRUE
```

**Comment by mvfki** [comment]
@Lei-Guo Would you mind sharing what shows when you run `head(Idents(sub_endo))` and `head(Idents(sub_E))`? That error message could be caused by using "double brackets" to subscribe "0" index from a list-like object. So if your Seurat Idents are zero-based numbers, converting them to a character factor object could be worth a try. But I could be wrong with the prediction of your issue.

Also, for other users who might also get a problem with `makeRiverplot()` in the future, please note that we are planning to deprecate this function because it seems this function is actually rarely used. We are currently actively updating `rliger` package, so hopefully, it'll get a big new release soon.

**Comment by Lei-Guo** [comment]
Thanks for the quick response, Yichen. Please see below. You guys are deprecating the makeRiverplot() function? That's a shame. That's the function that leads me to the liger package. I think it's a great function that allows comparing clusters between 2 datasets. Do you have any recommendations for good alternatives for comparing clusters between 2 datasets?

`> head(Idents(sub_endo))
AAACCCAAGGATTCAA-1_1 AAACCCAGTCTGTGTA-1_1 AAACGAAAGAACTGAT-1_1
                 EC3                  EC1                  EC1
AAACGAATCAGCAGAG-1_1 AAACGCTTCGTGTTCC-1_1 AAACGCTTCTATTGTC-1_1
                 EC2                  EC3                  EC3
Levels: EC3 EC1 EC2 EC4 EC5 LEC
> head(Idents(sub_E))
AAACCTGAGCCATCGC-1 AAACCTGTCCAGTATG-1 AAAGATGCAAGCCCAC-1 AAAGATGTCCCTAACC-1
                E1                 E2                 E1                 E1
AAAGCAACATTTGCCC-1 AAAGCAATCACAATGC-1
                E1                 E1
Levels: E1 E2 E3`

**Comment by Lei-Guo** [comment]
Thanks for your great help, Yichen. It works now.
