### ISSUE TITLE
makeFeatureMatrix is not in the package

### ISSUE THREAD

**Issue by emdann** [MacoskoLab/liger#123]
Hi, I am trying to preprocess scATAC data to gene level features as described in the scATAC + scRNA-seq vignette, but the function `makeFeatureMatrix` is not exported from the NAMESPACE.

**Comment by vkozareva** [comment]
Hello! Have you made sure to install the latest version of the package? We only recently added this functionality. Also this function appears in the RcppExports instead of the NAMESPACE.

**Comment by arutik** [comment]
Hi,

Just to let you know: I also experience this even after installing with ```install_github('MacoskoLab/liger')```

Sincerely,
Anna Arutyunyan

**Comment by vkozareva** [comment]
It appears that on some systems (perhaps due to the R version), R might not readily recognize package functions which are only exported by RcppExports. We'll add a NAMESPACE exported version of this function, but in the meantime, you should be able to access the functionality by using `liger:::makeFeatureMatrix`. Sorry about that!

**Comment by ankushs0128** [comment]
makeFeaturematrix not available any of the two functionality

gene.counts <- liger:::makeFeatureMatrix(genes.bc, barcodes)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'makeFeatureMatrix' not found
