### ISSUE TITLE
Problem with subsetLiger

### ISSUE THREAD

**Issue by JoseMMuino** [MacoskoLab/liger#125]
Dear MacosKolab,

Thanks for the amazing tool that you have developed.

 When I run subsetLiger I get the error "Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length"

The problem is that when I try to subset my liger object, one of the samples only have one cell. This means that it will be not a  "dgCMatrix" object anymore but a vector.
I see that you eliminate samples that have not cells with
   _missing <- sapply(raw.data, is.null)
    raw.data <- raw.data[!missing]_

I think that it will better to also eliminate elements that are not a dgCMatrix object

Best,
Jose

**Comment by jw156605** [comment]
I think that this may be a feature rather than a bug, since it doesn't make sense to perform subsequent analyses (such as iNMF factorization) when one dataset contains only a single cell. Perhaps a better solution would be to remove all cells from that dataset, or use different subset parameters so that more than one cell is left.
