### ISSUE TITLE
Can liger support  SCTranform?

### ISSUE THREAD

**Issue by zehualilab** [MacoskoLab/liger#127]
Can liger support  SCTranform?

**Comment by jw156605** [comment]
What do you mean by support?

**Comment by minigel** [comment]
I am also interested in this question, specifically whether Seurat objects that have been normalized with SCTransform, rather than the standard log-normalization, can be integrated with LIGER. The current vignette only describes the latter workflow: https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/liger.html

SCTransform outputs Pearson residuals that are used for integration with Seurat: (https://satijalab.org/seurat/v3.1/integration.html#sctransform). Can these residuals also be used as input to LIGER?
