### ISSUE TITLE
can i get a new dgcmatrix after integrading dataset by liger

### ISSUE THREAD

**Issue by EDGtentacles** [MacoskoLab/liger#163]
Thanks for your impressive work!
Although `ligerToSeurat`  makes great convenience in transferring a liger object to a seurat object, there are still lots of packages analysing single cell data. i just wonder can I get a new dgcmatrix after integrading dataset by liger.

**Comment by skpalan** [comment]
Of course you can! You can access every component of `liger` object that you are interested directly using typical `R` manners. Suppose you have a liger object `dge` that stores two datasets "rna" and "atac", here are some examples:
* to extract normalized RNA data: `dge@norm.data[["rna"]]`
* to extract scaled atac data: `dge@scale.data[["atac"]]`
* to extract normalized H matrix (shared latent space by iNMF): `dge@H.norm`

Also refer to our documentation of a typical `liger` object and its slots:
https://github.com/MacoskoLab/liger/blob/7e8c78b22a3f8e22ce60c10ad51fce17e3183416/R/liger.R#L5-L33

**Comment by kuang-da** [comment]
Suppose I used Liger to integrate two datasets (WT and KO), so I have two slots in liger@norm.data. May I do as following to export the normalized UMI matrix as the input of other clustering techniques?

Thank you very much!

```
traf6.norm.wt <- traf6.liger@norm.data$wt
traf6.norm.ko <- traf6.liger@norm.data$ko

common_gene <- intersect(row.names(traf6.norm.wt),row.names(traf6.norm.ko))
traf6.norm.wt <- traf6.norm.wt[common_gene, ]
traf6.norm.ko <- traf6.norm.ko[common_gene, ]

traf6.norm <- cbind(traf6.norm.wt, traf6.norm.ko)
```

**Comment by jw156605** [comment]
Perhaps the point of confusion here is that, unlike Seurat, **LIGER does not change the original gene expression data** after integration. The code you shared will export the normalized data slot from LIGER, but this is probably not what you want. You can certainly use this for clustering, but (1) if there are batch effects or biological differences (WT vs. KO) the normalized data will reflect these and (2) you almost certainly want to use the scaled data rather than the normalized data, because accounting for the differences in gene variance is crucial for downstream analyses.
