### ISSUE TITLE
About runWilcoxon and norm.data

### ISSUE THREAD

**Issue by kuang-da** [MacoskoLab/liger#167]
Hi, 

Thanks for providing liger, such a great tool for removing batch effects and downstream analysis. After testing the package and read the source code of runWilcoxon. I have a question about the implementation of the runWilcoxon function. It would be highly appreciated if I could get any insight here.

It seems that runWilcoxon finds marker genes based on the matrix in the slot named norm.data. Integrated data can be used for clustering but when it comes to DE analysis, is it possible that applying Wilcoxon on them may lead to some bias since the scaling of the data?

In Seurat, it is recommended to apply DE analysis on SCT normalized data instead of integrated data. [Ref: https://github.com/satijalab/seurat/issues/1836#issuecomment-513632072]

Would you mind explaining a little bit about the difference between runWilcoxon and Seurat's FindCluster if it is possible? 

Thanks for your time!

**Comment by jw156605** [comment]
Perhaps the point of confusion here is that, unlike Seurat, **LIGER does not change the original gene expression data after integration**. The runWilcoxon function operates on the normalized data slot from LIGER, using clusters jointly defined from all datasets. This is exactly analogous to the SCT normalized data that Seurat uses.

**Comment by jykr** [comment]
Hi! Thanks for the great package! 

I also have a question about runWilcoxon. It seems to me from the code and your comment that marker genes are found from the unadjusted original gene expression matrices. Is there a way to adjust for the batch effect (ex. Gene called as a marker in cluster 1 vs cluster 2 being just because the batch composition is different.) or is it already implemented in the way?

Thank you!

**Comment by cgao90** [comment]
Hi! Hope this previous discussion #70 would help.
