### ISSUE TITLE
selectGenes issue

### ISSUE THREAD

**Issue by tanya-karagiannis** [MacoskoLab/liger#179]
Hi,

I am trying to integrate RNA expression data and protein level expression data. When I tried to use the selectGenes function to identify highly variable genes only in the RNA expression data (dataset 1), the plot generated tells me there are 3400 genes selected. However the var.genes slot only has 6 genes. These 6 genes overlap with the protein level expression data. It looks like the selectGenes function is taking the intersection of the features between the two datasets. According to the tutorials and function arguments, it should be set up to select genes from only one dataset. Any suggestions of what I should check? 
The code and output I used is below:

```{r}
pbmc.liger <- selectGenes(pbmc.liger, datasets.use = 1, do.plot = TRUE)

```
Plot output:
![Screen Shot 2020-06-29 at 3 59 34 PM](https://user-images.githubusercontent.com/15644655/86050297-a8637980-ba21-11ea-91b0-7ced7510935c.png)

```{r}
pbmc.liger@var.genes
```
"FCGR3A" "CD8A"   "CD14"   "NCAM1"  "CD3D"   "CD19"  

Thanks,
Tanya

**Comment by skpalan** [comment]
Hi Tanya, in this case, you should set another parameter `keep.unique` to `True` in order to keep the unique genes from your RNA expression data (dataset 1). And yes, the plot generated only corresponds to each of the datasets individually. For example, the plot you provided shows that indeed 3400 genes were selected from dataset 1.
